all:
	cd grokking_algorithms_en && zip -r ../grokking_algorithms.epub * && cd ..
	cd grokking_algorithms_chinese && zip -r ../grokking_algorithms_chinese.epub * && cd ..
	cd grokking_algorithms_chinese-tw && zip -r ../grokking_algorithms_chinese-tw.epub * && cd ..
	cd grokking_artificial-intelligence-algorithms_en && zip -r ../grokking_artificial-intelligence-algorithms_en.epub *
		
clean:
	rm -f *.epub *~
